---
- name: Download - Check the downloaded file.
  ansible.builtin.stat:
    path: "{{ nexus_install_dir }}/nexus-unix.tar.gz"
  register: downloaded

- name: Download - Download Nexus installation file.
  ansible.builtin.get_url:
    url: "{{ nexus_download_url }}"
    dest: "{{ nexus_install_dir }}/nexus-unix.tar.gz"
  when: downloaded.stat.exists == false

- name: Download - Uncompress downloaded file.
  ansible.builtin.unarchive:
    src: "{{ nexus_install_dir }}/nexus-unix.tar.gz"
    dest: "{{ nexus_install_dir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"
    copy: no
  when: nexus_update or installed.stat.exists == false
