---
- name: Fabric - Ensure elasticsearch configuration is present.
  become: true
  ansible.builtin.template:
    src:  "elasticsearch.yml.j2"
    dest: "{{ nexus_install_dir }}/nexus/etc/fabric/elasticsearch.yml"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    mode: 0644
  notify: restart nexus service

