---
- name: Initd - Create init.d symlink.
  ansible.builtin.file:
    src: "{{ nexus_home_dir }}/bin/nexus"
    dest: "/etc/init.d/nexus"
    state: link
  register: initd_symlink

- name: Initd - update-rc.d nexus.
  ansible.builtin.command: "update-rc.d nexus defaults"
  changed_when: true
  when: initd_symlink.changed
  notify: Restart nexus service
