---
- find: path="{{ nexus_install_dir }}" patterns="nexus-*" file_type=directory
  register: installed_dir

- name: Installation - Versioned Nexus directory.
  set_fact:
    nexus_versioned_dir: "{{ installed_dir.files[installed_dir.matched-1].path }}"

- name: Installation - Ensure home_dir symlink is created.
  file:
    src: "{{ nexus_versioned_dir }}"
    dest: "{{ nexus_install_dir }}/nexus"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    state: link

- name: Installation - Ensure nexus user is owner of nexus directory.
  file:
    path: "{{ nexus_versioned_dir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    recurse: yes

- name: Installation - Check sonatype-work.
  stat: path="{{ nexus_install_dir }}/sonatype-work"
  register: sonatype_work

- name: Installation - Ensure nexus user is owner of sonatype-work.
  file:
    path: "{{ nexus_install_dir }}/sonatype-work"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    recurse: yes
  when: sonatype_work.stat.exists