---
- include_tasks: user.yml

- name: Ensure nexus is installed.
  stat: path="{{ nexus_home_dir }}/bin/nexus"
  register: installed

- include_tasks: download.yml
  when: nexus_update or installed.stat.exists == false

- include_tasks: installation.yml

- include_tasks: configuration.yml

- include_tasks: initd.yml

- name: Main -  Clean-up
  include_tasks: cleanup.yml
  when: nexus_cleanup == true
