---
- name: Check the downloaded file
  stat: path="{{ nexus_install_dir }}/nexus-unix.tar.gz"
  register: downloaded

- name: Download Nexus installation file 
  get_url: 
    url: "{{ nexus_download_url }}"
    dest: "{{ nexus_install_dir }}/nexus-unix.tar.gz"
  when: downloaded.stat.exists == false

- name: Uncompress downloaded file
  unarchive:
    src: "{{ nexus_install_dir }}/nexus-unix.tar.gz"
    dest: "{{ nexus_install_dir }}"
    copy: no

- find: path="{{ nexus_install_dir }}" patterns="nexus-*" file_type=directory
  register: installed_dir

- debug: var=installed_dir.files[0].path

- name: Create symlink
  file:
    src: "{{ installed_dir.files[0].path }}"
    dest: "{{ nexus_install_dir }}/nexus"
    state: link

- name: Remove downloaded file
  file: path="{{ nexus_install_dir }}/nexus-unix.tar.gz" state=present

- lineinfile:
    dest: "{{ nexus_install_dir }}/nexus/bin/nexus"
    regexp: "^INSTALL4J_JAVA_HOME_OVERRIDE="
    line: "INSTALL4J_JAVA_HOME_OVERRIDE=/usr/lib/jvm/java-8-oracle"

