---
- name: Ensure nexus group is created.
  ansible.builtin.group:
    name: "{{ nexus_group }}"

- name: Ensure nexus user is created
  ansible.builtin.user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    createhome: no

- name: Ensure nexus is installed.
  ansible.builtin.stat:
    path: "{{ nexus_home_dir }}/bin/nexus"
  register: installed

- name: Download Nexus
  ansible.builtin.include_tasks: download.yml
  when: nexus_update or installed.stat.exists == false

- name: Include tasks
  ansible.builtin.include_tasks: "{{ task }}"
  loop:
  - installation.yml
  - configuration.yml
  - vmoptions.yml
  - initd.yml
  - system_requirements.yml
  - systemd.yml
  - fabric.yml
  loop_control:
    loop_var: task

- name: Ensure nexus user shell and home are defined.
  ansible.builtin.user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    shell: "/bin/bash"
    home: "{{ nexus_home_dir }}"
    createhome: no

- name: Main -  Clean-up
  ansible.builtin.include_tasks: cleanup.yml
  when: nexus_cleanup == true
