---
- name: Ensure nexus group is created.
  group:
    name: "{{ nexus_group }}"

- name: Ensure nexus user is created
  user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    createhome: no

- name: Ensure nexus is installed.
  stat:
    path: "{{ nexus_home_dir }}/bin/nexus"
  register: installed

- include_tasks: download.yml
  when: nexus_update or installed.stat.exists == false

- include_tasks: "{{ task }}"
  loop:
  - installation.yml
  - configuration.yml
  - vmoptions.yml
  - initd.yml
  - system_requirements.yml
  - systemd.yml
  - fabric.yml
  loop_control:
    loop_var: task

- name: Ensure nexus user shell and home are defined.
  user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    shell: "/bin/bash"
    home: "{{ nexus_home_dir }}"
    createhome: no

- name: Main -  Clean-up
  include_tasks: cleanup.yml
  when: nexus_cleanup == true
