---
- name: System Requirements - Ensure PAM common session is configured.
  community.general.pamd:
    name: 'common-session'
    type: session
    control: required
    module_path: pam_limits.so
  notify: restart nexus service

- name: System Requirements - Ensure nexus is defined in PAM Limits.
  community.general.pam_limits:
    domain: 'nexus'
    limit_item: 'nofile'
    limit_type: '-'
    value: '65536'
  notify: restart nexus service
