---
- name: Systemd - Ensure service script is present.
  become: true
  ansible.builtin.template:
    src:  "nexus.systemd.j2"
    dest: "/lib/systemd/system/nexus.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart nexus service

- name: Systemd - Ensure service is linked into /etc/systemd.
  ansible.builtin.file:
    src: "/lib/systemd/system/nexus.service"
    dest: "/etc/systemd/system/nexus.service"
    state: link

- name: Systemd - Ensure service is linked into /etc/systemd/multi-user.target.wants.
  ansible.builtin.file:
    src: "/lib/systemd/system/nexus.service"
    dest: "/etc/systemd/system/multi-user.target.wants/nexus.service"
    state: link
